server.port=8082
spring.application.name=voicelk_be

# Load .env file as properties
spring.config.import=optional:file:.env[.properties]

# Supabase Datasource Configuration
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=voicelk_super_secret_key_change_this_in_production_min_256_bits_long_key
app.jwt.expiration=86400000